[package]
name = "solana-arbitrage-watcher"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
url = "2.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
